name: Test and Deploy

on:
  push:
    branches:
      - master

# env:
#   AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
#   ECR_REPOSITORY: ecs-devops-sandbox-repository           # set this to your Amazon ECR repository name
#   ECS_SERVICE: ecs-devops-sandbox-service                 # set this to your Amazon ECS service name
#   ECS_CLUSTER: ecs-devops-sandbox-cluster                 # set this to your Amazon ECS cluster name
#   ECS_TASK_DEFINITION: task-definition.json # set this to the path to your Amazon ECS task definition
#                                                # file, e.g. .aws/task-definition.json
#   CONTAINER_NAME: ecs-devops-sandbox           # set this to the name of the container in the
                                                # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
